import './globals.css'

import type { Metadata } from 'next'

import { Background3D } from '@/libs/components/Background3D'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className="relative h-screen w-screen">
          <Background3D />
        </div>
        <div className="absolute top-0">{children}</div>
      </body>
    </html>
  )
}
